# Generated by Django 5.2.5 on 2025-08-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
